config/routes.rb
Rails.application.routes.draw do
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks', to: 'tasks#create'

  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  def completed?
    self.completed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :delete]
  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', style: 'margin-bottom: 10px;' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control', style: 'margin-bottom: 10px;' %>
  </div>

  <% if controller.action_name == 'edit' %>
    <div class="form-group">
      <%= f.label :completed, style: 'margin-bottom: 10px;' do %>
        <%= f.check_box :completed %>
        Completed
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'action-btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= render "form", task: @task, class: 'action-btn' %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul class="task-list">
  <% @tasks.each do |task| %>
    <li>
      <%= check_box_tag "task_ids[]", task.id, false, class: "task-checkbox" %>
      <%= link_to task.title, task_path(task.id) %>
    </li>
  <% end %>
</ul>

<%= link_to ' Create Task', new_task_path %>

app/views/tasks/new.html.erb
<h2>Create new Task</h2>
<%= render "form", task: @task, class: 'action-btn' %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed? ? 'This task is completed' : 'This task is not completed yet' %></p>
<%= link_to 'Back to list', tasks_path, class: 'action-btn' %>
<%= link_to 'Edit Task', edit_task_path, class: 'action-btn' %>
<%= link_to "Delete Task",
 		 destroy_task_path(@task), class: 'action-btn',
 		 data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>